// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrotryyusknbtszgkrua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyb3RyeXl1c2tuYnRzemdrcnVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTk2NDUsImV4cCI6MjA3MTUzNTY0NX0.DgSQ-kh41mZPfzX3cCXhGsuVls2sJ4EbGfnUSpJSQro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});